---
phdz_secure_home_allow_missing: true

# If true, enforce owner/group/mode on the user's home directory itself (no recursion).
phdz_secure_home_lock_home: true

# Mode to enforce on the user's home directory itself (no recursion).
phdz_secure_home_home_mode: '0700'

phdz_secure_home_dirs_default:
  - .ssh
  - .gnupg
  - .password-store

phdz_secure_home_dirs_extra: []

phdz_secure_home_dirs: '{{ phdz_secure_home_dirs_default + phdz_secure_home_dirs_extra }}'
