---
phdz_linux_baseline_default_packages:
  - ca-certificates
  - curl
  - git
  - gnupg
  - gpg-agent
  - less
  - makepasswd
  - sudo
  - tmux
  - tree
  - unzip
  - vim
  - wget
  - whois # provides mkpasswd for Argon2 password hashing
  - yq
  - zip
  - zsh

phdz_linux_baseline_packages: []
phdz_linux_baseline_upgrade: false
phdz_linux_baseline_services: []
phdz_linux_baseline_default_alternatives:
  editor: /usr/bin/vim.basic
  vi: /usr/bin/vim.basic
  view: /usr/bin/vim.basic
phdz_linux_baseline_alternatives: {}
