---
- hosts: all
  name: User level configuration (does not run as sudo)
  gather_facts: true
  become: false
  roles:
    - phdz_homeshick

# - hosts: all
#   roles:
#     - home
#
#   vars_files:
#     - ['vars/os-{{ ansible_os_family }}.yaml', vars/os-defaults.yaml]
#     - vars/all.yaml
#     #- vars/simple-variants.yaml
...
