---
- name: User level configuration (does not run as sudo)
  become: false
  gather_facts: true
  hosts: all
  roles:
    - phdz_homeshick
    - phdz_gpg_keys
    - phdz_ssh_keys
    - phdz_nix_home_manager
    - phdz_secure_home # Should almost always be last

...
