---
molecule_prepare_apt_packages:
  - git
  - gnupg
  - gpg-agent
  - zsh

phdz_gpg_keys_ultimate_trust: true
phdz_gpg_keys_public:
  - |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mDMEaWRIRhYJKwYBBAHaRw8BAQdAOG9Xpd7facVlZ+9QXWcfdIvdhy7ei9OJBDUM
    xxkl1u60JFN1YmtleSBUZXN0IDxzdWJrZXlAZXhhbXBsZS5pbnZhbGlkPoiTBBMW
    CgA7FiEEOT/YtPa6l6RuMyRGNgHNzaqLKNYFAmlkSEYCGwEFCwkIBwICIgIGFQoJ
    CAsCBBYCAwECHgcCF4AACgkQNgHNzaqLKNYF8gEAsdhYyOLoZf/GoQComgOavXDb
    agjAq1if6sdsMV8F//IA/1aUiDnrnaSz3Qq2JMQl5FyoqYSEnNMJ1bHXSyROLycF
    uDgEaWRIjBIKKwYBBAGXVQEFAQEHQPUTrfphf6S0a+fZb6+qGds4cdhVrYXeFeQ2
    g5+gjwYsAwEIB4h4BBgWCgAgFiEEOT/YtPa6l6RuMyRGNgHNzaqLKNYFAmlkSIwC
    GwwACgkQNgHNzaqLKNbCZAEAhe427WzJB7q2yDHynCxt0wJb7BFMdGu23i5TZGMZ
    VpQA/1Fp4AVZ6kc2/R6XcEcq4AkAgwA4gendo9Ir0HuhO4UBuDMEaWRImhYJKwYB
    BAHaRw8BAQdAU0T3voe75iqKfVDCAzLHdMmS+ha9h2F2KYzaXEdXOkaI7wQYFgoA
    IBYhBDk/2LT2upekbjMkRjYBzc2qiyjWBQJpZEiaAhsCAIEJEDYBzc2qiyjWdiAE
    GRYKAB0WIQSXG4rTIwzUiPLUAG1wKpKa4mZKcgUCaWRImgAKCRBwKpKa4mZKcoeG
    AP4mQBZkQ4xHHy62ey6kPhy2V+YMcFpCovXWXbq/cFQd/QEAqzUma2/IYqMKOdHc
    AOTxYl+TyLOOEj0fBY5anAcf6whlFwEAtuOmRMOO7xlFpzAN3MdNsZlwoVYEG3yp
    IABINR861fwBANGdTiDQD3PiIth4q4lvO0/SDuMSV+cDyw1qwN51Yp0N
    =h1tf
    -----END PGP PUBLIC KEY BLOCK-----
  - |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mDMEaWNVUxYJKwYBBAHaRw8BAQdAv1g6f9iutPb46AD9UnbA8uORgdLrq1Oz5Zds
    cf/ZYai0LER1bW15IFRlc3QgS2V5ICgxKSA8ZHVtbXktMUBleGFtcGxlLmludmFs
    aWQ+iJMEExYKADsWIQROJBou1tSIP+bZIMos6Dlnf5NNLAUCaWNVUwIbAwULCQgH
    AgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRAs6Dlnf5NNLNyMAP4zAo3xnSGk8OEJ
    3DBWMhUdSLNQ225XY20JZePzN3kzgAEAy8U6a931vm8iNu6y5Cqu9V20W5k3l2/7
    z8pcPQtAywk=
    =F/Zy
    -----END PGP PUBLIC KEY BLOCK-----
  - |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mDMEaWNVXhYJKwYBBAHaRw8BAQdA3uzbnG9G4jCyhGBD7CE3nbmTcU66evLupuHw
    wc0Bpuq0LER1bW15IFRlc3QgS2V5ICgyKSA8ZHVtbXktMkBleGFtcGxlLmludmFs
    aWQ+iJMEExYKADsWIQTeC64/kmaBuiF0IR6k1GXmxf7RSgUCaWNVXgIbAwULCQgH
    AgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRCk1GXmxf7RShFKAP0ecYiBumkpMvOO
    L0u33HD2Af+jkqHhSLhtoe4qLdsVzQEAub8zeKQkaq4GlikVAtWbyn4RzCmIF+Wh
    RugJ2C5iDQ0=
    =FJZy
    -----END PGP PUBLIC KEY BLOCK-----
  - |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mDMEaWNVZBYJKwYBBAHaRw8BAQdA30lJ/KpSGa0phjHoOPiBoRIO82ozIOtwjg2I
    qGayGte0LER1bW15IFRlc3QgS2V5ICgzKSA8ZHVtbXktM0BleGFtcGxlLmludmFs
    aWQ+iJMEExYKADsWIQT/J9BlZ3dBYt2orPZtKmfHcSDo1AUCaWNVZAIbAwULCQgH
    AgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRBtKmfHcSDo1DeAAP98ykcfEUklHn36
    EvRPbnHA6ioTmsgjyjsUtuBsd/qGUwD9G7uUyUGviGehKMgIdr7AwnPtxVC8eo1L
    Ebwn1lWAhg0=
    =Z52X
    -----END PGP PUBLIC KEY BLOCK-----
...
