---
phdz_defaults_become_for_all: false
phdz_defaults_force_upgrade_all: false
phdz_defaults_prefix: /opt/devenv

phdz_defaults_packages_update_cache: false

_phdz_defaults_go_arch_command: eval "$(go env)"; echo $GOHOSTARCH
_phdz_defaults_go_platform_command: eval "$(go env)"; echo $GOOS
...
