---
- name: Manage authorized_keys entries
  ansible.builtin.include_tasks: authorized_keys.yaml
  when: phdz_ssh_keys_authorized_keys | length > 0

- name: Manage known_hosts entries
  ansible.builtin.include_tasks: known_hosts.yaml
  when: phdz_ssh_keys_known_hosts | length > 0
